import {
  LayoutDashboard,
  CalendarRange,
  UserCheck,
  Users,
  FileText,
  Trophy,
  Timer,
  Settings,
  Download,
  BarChart3,
  Home,
  BookOpenCheck,
  ClipboardList,
  Clock,
  History,
  LineChart,
  ListChecks,
  CalendarClock,
  FolderTree,
  ShieldOff,
  ShieldCheck,
} from "lucide-react";
import type { SubNavItem } from "./kit";

export const adminExamBatchNav: SubNavItem[] = [
  { title: "Dashboard", to: "/admin/exam-batch", icon: LayoutDashboard },
  { title: "Sessions", to: "/admin/exam-batch/sessions", icon: CalendarRange },
  { title: "Academic", to: "/admin/exam-batch/academic", icon: FolderTree },
  { title: "Enrollment", to: "/admin/exam-batch/enrollment", icon: UserCheck },
  { title: "Students", to: "/admin/exam-batch/students", icon: Users },
  { title: "Subject Manager", to: "/admin/exam-batch/subject-manager", icon: BookOpenCheck },
  { title: "Subject Progress", to: "/admin/exam-batch/subject-progress", icon: LineChart },
  { title: "Attendance", to: "/admin/exam-batch/attendance", icon: ShieldOff },
  { title: "Verification Content", to: "/admin/exam-batch/verification-content", icon: ShieldCheck },
  { title: "Exams", to: "/admin/exam-batch/exams", icon: FileText },
  { title: "Question Bank", to: "/admin/exam-batch/mcqs", icon: BookOpenCheck },
  { title: "Leaderboard", to: "/admin/exam-batch/leaderboard", icon: Trophy },
  { title: "Countdown", to: "/admin/exam-batch/countdown", icon: Timer },
  { title: "Downloads", to: "/admin/exam-batch/downloads", icon: Download },
  { title: "Analytics", to: "/admin/exam-batch/analytics", icon: BarChart3 },
  { title: "Settings", to: "/admin/exam-batch/settings", icon: Settings },
];

export const studentExamBatchNav: SubNavItem[] = [
  { title: "Home", to: "/exam-batch", icon: Home },
  { title: "Subjects", to: "/exam-batch/subjects", icon: BookOpenCheck },
  { title: "Verification", to: "/exam-batch/enrollment", icon: ClipboardList },
  { title: "Pending", to: "/exam-batch/pending", icon: Clock },
  { title: "Exam Dashboard", to: "/exam-batch/dashboard", icon: LayoutDashboard },
  { title: "Available", to: "/exam-batch/available", icon: ListChecks },
  { title: "Upcoming", to: "/exam-batch/upcoming", icon: CalendarClock },
  { title: "Leaderboard", to: "/exam-batch/leaderboard", icon: Trophy },
  { title: "Progress", to: "/exam-batch/progress", icon: LineChart },
  { title: "History", to: "/exam-batch/history", icon: History },
];
